### ISSUE TITLE
Sorting is not uniform over all letters and numbers

### ISSUE THREAD

**Issue by ToreyHilbert** [ashleypancho/countdown-app#26]
Hi,

In the sorting in lines 56-57 in the letters.components.ts https://github.com/ashleypancho/countdown-app/blob/490dbbe7bafd085bc37c6056f5a3b7a48234c941/countdown/src/app/letters/letters.component.ts#L56-L57 This sort favors earlier letters over later letters. Similarly for the numbers.components.ts lines 63-64 https://github.com/ashleypancho/countdown-app/blob/490dbbe7bafd085bc37c6056f5a3b7a48234c941/countdown/src/app/numbers/numbers.component.ts#L63-L64

See for example, here: https://javascript.info/task/shuffle

I recommend simply copying the function from here: https://www.geeksforgeeks.org/how-to-shuffle-an-array-using-javascript/

Have a great day!

**Comment by ashleypancho** [comment]
Hey, thanks for the suggestion! 

You're totally right, there are definitely other / better ways to achieve a randomized result set, and I've seen this need become evident over a lot of testing. 

Some factor of this was, "hey, let's get an MVP out so people can test and play and I can make it better later," so thanks for testing and providing some suggestion on how to make it better. I'll definitely take a look at the shuffle links. It's not something I have to do every day for work 🙂

Hope you're enjoying the game otherwise!
